# Generated by Django 5.2.6 on 2025-09-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='option',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
