# Generated by Django 5.2.6 on 2025-09-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_choice_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='public_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
