# Generated by Django 5.2.6 on 2025-09-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_question_public_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='public_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
